# -*- coding: utf-8 -*-
"""Copy of WEAK 0_SET 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsC1mDJNk_4YPLbiTymqa7haNFkTTofq

SET 1

CHALLENGE 1
"""

import base64

hex_data = "49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d"

bytes_data = bytes.fromhex(hex_data)

base64_data = base64.b64encode(bytes_data)

print(base64_data.decode())

"""CHALLENGE 2"""

hex1 = "1c0111001f010100061a024b53535009181c"
hex2 = "686974207468652062756c6c277320657965"

b1 = bytes.fromhex(hex1)
b2 = bytes.fromhex(hex2)

result = bytes(a ^ b for a, b in zip(b1, b2))


print(result.hex())

"""CHALLENGE 3"""

cipher_hex = "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736"

cipher_bytes = bytes.fromhex(cipher_hex)

key = ord('A')

decoded = ''.join(chr(b ^ key) for b in cipher_bytes)

print(decoded)

cipher_hex = "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736"

cipher_bytes = bytes.fromhex(cipher_hex)

key = ord('X')

decoded = ''.join(chr(b ^ key) for b in cipher_bytes)

print(decoded)

"""CHALLENGE 5"""

plaintext = """Burning 'em, if you ain't quick and nimble
I go crazy when I hear a cymbal"""

key = "ICE"

result = ""

for i in range(len(plaintext)):

    p = ord(plaintext[i])

    k = ord(key[i % len(key)])

    xor_value = p ^ k

    result += format(xor_value, '02x')

print(result)

"""CHALLENGE 7"""

!pip install pycryptodome

from google.colab import files

uploaded = files.upload()

!pip install pycryptodome

from Crypto.Cipher import AES
import base64

# Read encrypted file
with open("7[1] (3).txt", "r") as f:
    data = f.read()

# Base64 decode
ciphertext = base64.b64decode(data)

# AES key
key = b"YELLOW SUBMARINE"

# Create AES ECB cipher
cipher = AES.new(key, AES.MODE_ECB)

# Decrypt
plaintext = cipher.decrypt(ciphertext)

# Print result
print(plaintext.decode())